CI: pin to Hugo 0.145.0
0.146 had breaking changes again, this time missing a template:
Error: error building site: html/template:single.html:94:24: no such template "_internal/disqus.html"

Signed-off-by: Daniel Maslowski <info@orangecms.org>